# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.

jobs:
  docker_lint:
    working_directory: /root/project
    docker:
      - image: hadolint/hadolint
    steps:
      - checkout
      - run: 
          name: Run hadolint on dockerfile
          command: hadolint Dockerfile
      - run:
          name: Test Markdown Files
          ommand: |
            wget https://github.com/felicianotech/md-proofer/releases/download/v0.3.0/md-proofer--v0.3.0--linux-amd64.tar.gz
            tar xfz md-proofer-v*.tar.gz
            sudo chmod +x ./md-proofer
            echo "===================================================================================="
            ./md-proofer lint
  build:
    machine: true
    steps:
      - checkout
      - run: docker build . --file Dockerfile --tag bl0m1/xtevedocker-ci:ci-latest
      - run: echo "$DOCKER_PASS" | docker login --username bl0m1 --password-stdin
      - run: docker push bl0m1/xtevedocker-ci:ci-latest
  test:
    working_directory: /xteve
    docker:
      - image: bl0m1/xtevedocker-ci:ci-latest
    steps:
      - run: ./xteve -info
      - run: cat /home/xteve/.xteve/settings.json

workflows:
  version: 2
  build_and_test:
    jobs:
      - docker_lint
      - build:
          requires:
            - docker_lint
      - test:
          requires:
            - build
